version: '3.8'

services:
  # FastAPI Application
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: legal_advocacy_api
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      API_HOST: 0.0.0.0
      API_PORT: 8000
    ports:
      - "8003:8000"
    volumes:
      - audio_files:/app/audio_files
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - legal_advocacy_network

# Top-level declaration for networks
networks:
  legal_advocacy_network:
    driver: bridge

# Top-level declaration for named volumes
volumes:
  audio_files: